import pandas as pd

pd.set_option('display.max_rows', None)

def tab(df, variable, include_all=False):
    """
    Tabulate a variable, with an option to include all possible values.

    Parameters:
    - df: The DataFrame containing the data.
    - variable: The column name of the variable to tabulate.
    - include_all: Boolean flag indicating whether to include all values or only observed ones.

    Prints:
    - A formatted tabulation of the variable, sorted by Value.
    - A separate summary of NaN values, if they exist.
    - A final row indicating the number of observations excluding NaN.
    """
    if include_all:
        # Get all unique values including NaN
        unique_values = df[variable].unique()
        
        # Ensure all unique values are included
        all_values_df = pd.DataFrame({variable: unique_values})
        
        # Tabulate the variable, including NaN counts
        value_counts = df[variable].value_counts(dropna=False).reset_index()
        
        # Rename the columns
        value_counts.columns = ['Value', 'Frequency']
        
        # Merge with all_values_df to ensure all values are present
        tabulation = pd.merge(all_values_df, value_counts, how='left', left_on=variable, right_on='Value')
        
        # Fill NaN frequencies with 0
        tabulation['Frequency'].fillna(0, inplace=True)
        
        # Drop the extra 'Value' column generated by the merge
        tabulation.drop(columns=[variable], inplace=True)
    else:
        # Tabulate only the observed values
        tabulation = df[variable].value_counts(dropna=False).reset_index()
        tabulation.columns = ['Value', 'Frequency']

    # Sort the tabulation by the actual Value
    tabulation = tabulation.sort_values(by='Value').reset_index(drop=True)

    # Calculate the percentage
    tabulation['Percent'] = (tabulation['Frequency'] / tabulation['Frequency'].sum()) * 100
    
    # Calculate the cumulative percentage based on the sorted order
    tabulation['Cumulative Percent'] = tabulation['Percent'].cumsum()

    # Separate out the NaN values
    nan_frequency = df[variable].isna().sum()
    nan_percent = (nan_frequency / len(df)) * 100

    # Exclude NaN from the main tabulation
    tabulation = tabulation[~tabulation['Value'].isna()].reset_index(drop=True)

    # Calculate total observations excluding NaN
    total_observations = tabulation['Frequency'].sum()
    total_percent = 100 - nan_percent

    # Print the main tabulation
    print(tabulation.to_string(index=False))
    print('------------------------------------------------------------------')    
    # Custom formatted output
    print(f"{'Total Non-missing:':<20} {total_observations:>10,}  {'Percent:':<10} {total_percent:>6.2f}")
    print(f"{'Missing values:':<20} {nan_frequency:>10,}  {'Percent:':<10} {nan_percent:>6.2f}")
